---
# The following tasks are used to install redis cluster management software
#
- name: Install redis gem
  package:
    name: rubygem-redis
  when: ansible_facts['os_family'] != "Debian"

- name: Install redis gem
  apt:
    name: ruby-redis
  when: ansible_facts['os_family'] == "Debian"
  
- name: Install redis-trib from localfile.
  copy:
    src: redis-trib
    dest: /usr/bin/redis-trib
    mode: 0755

- name: print node list
  debug:
    msg: "{{ redis_node_list }}"


# link the cluster together.
- name: Create cluster with all nodes
  shell: "redis-trib create --yes --replicas {{ redis_cluster_replicas }} {{ redis_node_list | join(' ') }} && touch {{ redis_conf_dir }}/redis-cluster-created"
  args:
    creates: "{{ redis_conf_dir }}/redis-cluster-created"
